---
# action.yml
name: 'Generate Report'
author: 'Ryan Long <ryan.long@noaa.gov>'
description: 'Generates a graphical web report from binary traces in the version directory'
inputs:
  report-name:  
    description: 'Name of the report'
    required: false
    default: 'default-report'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'go.sh'
    
branding:
  icon: 'code'
  color: 'yellow'


